name: Java and Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # GitHub Actionsのタイムラインの可視化
    - uses: Kesin11/actions-timeline@v2

    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: |
          17
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle Cacge
      uses: gradle/gradle-build-action@v3
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build library
      run: ./gradlew :mfm_kt:build

    - name: Test
      run: ./gradlew :mfm_kt:test

    # Generates a debug APK
    - name: Build Sample Activity (debug version only)
      run: ./gradlew :sample_activity:assembleDebug
